### ISSUE TITLE
Error handling and feedback mechanisms

### ISSUE THREAD

**Issue by martinthomson** [EricssonResearch/Blind-Cache-Drafts#4]
The feedback mechanisms are sketchy.  Similar efforts to define these have failed in the past.

**Comment by reschke** [comment]
They are optional right now, and seem relatively harmless. I have implemented parts of this.

Maybe move to an appendix for now?

**Comment by gaperik** [comment]
As we said on the editor meeting, move to appendix for now. Consider mentioning that it is left to the client to implement and upload relevant statistics leveraging browser/device OS mechanisms.
